services:
  mongodb:
    container_name: "mongodb"
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${ADMIN_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${ADMIN_PASS}
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  linkroll:
    container_name: "linkroll"
    image: linkroll:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

volumes:
  mongodb-data: